# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: virk/indberetning.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from types import date_pb2 as types_dot_date__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='virk/indberetning.proto',
  package='asdf.virk',
  syntax='proto3',
  serialized_options=b'Z\032github.com/hroi/proto/virk',
  serialized_pb=b'\n\x17virk/indberetning.proto\x12\tasdf.virk\x1a\x10types/date.proto\"y\n\x0cIndberetning\x12\x17\n\x0findberetning_id\x18\x01 \x01(\x03\x12\x0b\n\x03_id\x18\x02 \x01(\t\x12\x12\n\nsagsnummer\x18\x03 \x01(\t\x12/\n\x10regnskabsperiode\x18\x04 \x01(\x0b\x32\x15.asdf.types.DaterangeB\x1cZ\x1agithub.com/hroi/proto/virkb\x06proto3'
  ,
  dependencies=[types_dot_date__pb2.DESCRIPTOR,])




_INDBERETNING = _descriptor.Descriptor(
  name='Indberetning',
  full_name='asdf.virk.Indberetning',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='indberetning_id', full_name='asdf.virk.Indberetning.indberetning_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='_id', full_name='asdf.virk.Indberetning._id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sagsnummer', full_name='asdf.virk.Indberetning.sagsnummer', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='regnskabsperiode', full_name='asdf.virk.Indberetning.regnskabsperiode', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=177,
)

_INDBERETNING.fields_by_name['regnskabsperiode'].message_type = types_dot_date__pb2._DATERANGE
DESCRIPTOR.message_types_by_name['Indberetning'] = _INDBERETNING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Indberetning = _reflection.GeneratedProtocolMessageType('Indberetning', (_message.Message,), {
  'DESCRIPTOR' : _INDBERETNING,
  '__module__' : 'virk.indberetning_pb2'
  # @@protoc_insertion_point(class_scope:asdf.virk.Indberetning)
  })
_sym_db.RegisterMessage(Indberetning)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
