# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: virk/indberetning.proto

require 'google/protobuf'

require 'types/date_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("virk/indberetning.proto", :syntax => :proto3) do
    add_message "asdf.virk.Indberetning" do
      optional :indberetning_id, :int64, 1
      optional :_id, :string, 2
      optional :sagsnummer, :string, 3
      optional :regnskabsperiode, :message, 4, "asdf.types.Daterange"
    end
  end
end

module Asdf
  module Virk
    Indberetning = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asdf.virk.Indberetning").msgclass
  end
end
