# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types/date.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("types/date.proto", :syntax => :proto3) do
    add_message "asdf.types.Date" do
      optional :year, :int32, 1
      optional :month, :int32, 2
      optional :day, :int32, 3
    end
    add_message "asdf.types.Daterange" do
      optional :from, :message, 1, "asdf.types.Date"
      optional :to, :message, 2, "asdf.types.Date"
    end
  end
end

module Asdf
  module Types
    Date = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asdf.types.Date").msgclass
    Daterange = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asdf.types.Daterange").msgclass
  end
end
