# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types/date.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='types/date.proto',
  package='asdf.types',
  syntax='proto3',
  serialized_options=b'Z\033github.com/hroi/proto/types',
  serialized_pb=b'\n\x10types/date.proto\x12\nasdf.types\"0\n\x04\x44\x61te\x12\x0c\n\x04year\x18\x01 \x01(\x05\x12\r\n\x05month\x18\x02 \x01(\x05\x12\x0b\n\x03\x64\x61y\x18\x03 \x01(\x05\"I\n\tDaterange\x12\x1e\n\x04\x66rom\x18\x01 \x01(\x0b\x32\x10.asdf.types.Date\x12\x1c\n\x02to\x18\x02 \x01(\x0b\x32\x10.asdf.types.DateB\x1dZ\x1bgithub.com/hroi/proto/typesb\x06proto3'
)




_DATE = _descriptor.Descriptor(
  name='Date',
  full_name='asdf.types.Date',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='year', full_name='asdf.types.Date.year', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='month', full_name='asdf.types.Date.month', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='day', full_name='asdf.types.Date.day', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=80,
)


_DATERANGE = _descriptor.Descriptor(
  name='Daterange',
  full_name='asdf.types.Daterange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='from', full_name='asdf.types.Daterange.from', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to', full_name='asdf.types.Daterange.to', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=155,
)

_DATERANGE.fields_by_name['from'].message_type = _DATE
_DATERANGE.fields_by_name['to'].message_type = _DATE
DESCRIPTOR.message_types_by_name['Date'] = _DATE
DESCRIPTOR.message_types_by_name['Daterange'] = _DATERANGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Date = _reflection.GeneratedProtocolMessageType('Date', (_message.Message,), {
  'DESCRIPTOR' : _DATE,
  '__module__' : 'types.date_pb2'
  # @@protoc_insertion_point(class_scope:asdf.types.Date)
  })
_sym_db.RegisterMessage(Date)

Daterange = _reflection.GeneratedProtocolMessageType('Daterange', (_message.Message,), {
  'DESCRIPTOR' : _DATERANGE,
  '__module__' : 'types.date_pb2'
  # @@protoc_insertion_point(class_scope:asdf.types.Daterange)
  })
_sym_db.RegisterMessage(Daterange)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
