# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xbrl/v2/date.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='xbrl/v2/date.proto',
  package='asdf.xbrl.v2',
  syntax='proto3',
  serialized_options=b'Z\035github.com/hroi/proto/xbrl/v2',
  serialized_pb=b'\n\x12xbrl/v2/date.proto\x12\x0c\x61sdf.xbrl.v2\"0\n\x04\x44\x61te\x12\x0c\n\x04year\x18\x01 \x01(\x05\x12\r\n\x05month\x18\x02 \x01(\x05\x12\x0b\n\x03\x64\x61y\x18\x03 \x01(\x05\"N\n\x08\x44uration\x12!\n\x05start\x18\x01 \x01(\x0b\x32\x12.asdf.xbrl.v2.Date\x12\x1f\n\x03\x65nd\x18\x02 \x01(\x0b\x32\x12.asdf.xbrl.v2.DateB\x1fZ\x1dgithub.com/hroi/proto/xbrl/v2b\x06proto3'
)




_DATE = _descriptor.Descriptor(
  name='Date',
  full_name='asdf.xbrl.v2.Date',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='year', full_name='asdf.xbrl.v2.Date.year', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='month', full_name='asdf.xbrl.v2.Date.month', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='day', full_name='asdf.xbrl.v2.Date.day', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=84,
)


_DURATION = _descriptor.Descriptor(
  name='Duration',
  full_name='asdf.xbrl.v2.Duration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='asdf.xbrl.v2.Duration.start', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='asdf.xbrl.v2.Duration.end', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=164,
)

_DURATION.fields_by_name['start'].message_type = _DATE
_DURATION.fields_by_name['end'].message_type = _DATE
DESCRIPTOR.message_types_by_name['Date'] = _DATE
DESCRIPTOR.message_types_by_name['Duration'] = _DURATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Date = _reflection.GeneratedProtocolMessageType('Date', (_message.Message,), {
  'DESCRIPTOR' : _DATE,
  '__module__' : 'xbrl.v2.date_pb2'
  # @@protoc_insertion_point(class_scope:asdf.xbrl.v2.Date)
  })
_sym_db.RegisterMessage(Date)

Duration = _reflection.GeneratedProtocolMessageType('Duration', (_message.Message,), {
  'DESCRIPTOR' : _DURATION,
  '__module__' : 'xbrl.v2.date_pb2'
  # @@protoc_insertion_point(class_scope:asdf.xbrl.v2.Duration)
  })
_sym_db.RegisterMessage(Duration)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
