# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xbrl/v2/entity.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='xbrl/v2/entity.proto',
  package='asdf.xbrl.v2',
  syntax='proto3',
  serialized_options=b'Z\035github.com/hroi/proto/xbrl/v2',
  serialized_pb=b'\n\x14xbrl/v2/entity.proto\x12\x0c\x61sdf.xbrl.v2\",\n\x06\x45ntity\x12\x0e\n\x06scheme\x18\x01 \x01(\t\x12\x12\n\nidentifier\x18\x02 \x01(\tB\x1fZ\x1dgithub.com/hroi/proto/xbrl/v2b\x06proto3'
)




_ENTITY = _descriptor.Descriptor(
  name='Entity',
  full_name='asdf.xbrl.v2.Entity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scheme', full_name='asdf.xbrl.v2.Entity.scheme', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='identifier', full_name='asdf.xbrl.v2.Entity.identifier', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['Entity'] = _ENTITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Entity = _reflection.GeneratedProtocolMessageType('Entity', (_message.Message,), {
  'DESCRIPTOR' : _ENTITY,
  '__module__' : 'xbrl.v2.entity_pb2'
  # @@protoc_insertion_point(class_scope:asdf.xbrl.v2.Entity)
  })
_sym_db.RegisterMessage(Entity)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
