# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xbrl/v2/fact.proto

require 'google/protobuf'

require 'xbrl/v2/date_pb'
require 'xbrl/v2/concept_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("xbrl/v2/fact.proto", :syntax => :proto3) do
    add_message "asdf.xbrl.v2.Scenario" do
      repeated :members, :message, 1, "asdf.xbrl.v2.Scenario.Member"
    end
    add_message "asdf.xbrl.v2.Scenario.TypedMember" do
      optional :dimension, :enum, 1, "asdf.xbrl.v2.Concept"
      optional :type, :enum, 2, "asdf.xbrl.v2.Concept"
      optional :member, :string, 3
    end
    add_message "asdf.xbrl.v2.Scenario.ExplicitMember" do
      optional :dimension, :enum, 1, "asdf.xbrl.v2.Concept"
      optional :type, :enum, 2, "asdf.xbrl.v2.Concept"
    end
    add_message "asdf.xbrl.v2.Scenario.Member" do
      oneof :member do
        optional :typed, :message, 1, "asdf.xbrl.v2.Scenario.TypedMember"
        optional :explicit, :message, 2, "asdf.xbrl.v2.Scenario.ExplicitMember"
      end
    end
    add_message "asdf.xbrl.v2.Fact" do
      optional :instance_id, :int64, 1
      optional :scenario, :message, 4, "asdf.xbrl.v2.Scenario"
      optional :unit, :string, 5
      optional :lang, :string, 6
      optional :concept, :enum, 7, "asdf.xbrl.v2.Concept"
      oneof :Period do
        optional :period, :message, 2, "asdf.xbrl.v2.Duration"
        optional :instant, :message, 3, "asdf.xbrl.v2.Date"
      end
      oneof :value do
        optional :string, :string, 8
        optional :float64, :double, 9
        optional :date, :message, 10, "asdf.xbrl.v2.Date"
        optional :enum, :string, 11
      end
    end
  end
end

module Asdf
  module Xbrl
    module V2
      Scenario = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asdf.xbrl.v2.Scenario").msgclass
      Scenario::TypedMember = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asdf.xbrl.v2.Scenario.TypedMember").msgclass
      Scenario::ExplicitMember = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asdf.xbrl.v2.Scenario.ExplicitMember").msgclass
      Scenario::Member = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asdf.xbrl.v2.Scenario.Member").msgclass
      Fact = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asdf.xbrl.v2.Fact").msgclass
    end
  end
end
