// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.0
// 	protoc        v3.11.4
// source: xbrl/v2/fact.proto

package v2

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Scenario struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Members []*Scenario_Member `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *Scenario) Reset() {
	*x = Scenario{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xbrl_v2_fact_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Scenario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scenario) ProtoMessage() {}

func (x *Scenario) ProtoReflect() protoreflect.Message {
	mi := &file_xbrl_v2_fact_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scenario.ProtoReflect.Descriptor instead.
func (*Scenario) Descriptor() ([]byte, []int) {
	return file_xbrl_v2_fact_proto_rawDescGZIP(), []int{0}
}

func (x *Scenario) GetMembers() []*Scenario_Member {
	if x != nil {
		return x.Members
	}
	return nil
}

type Fact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstanceId int64 `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// Types that are assignable to Period_:
	//	*Fact_Period
	//	*Fact_Instant
	Period_  isFact_Period_ `protobuf_oneof:"Period"`
	Scenario *Scenario      `protobuf:"bytes,4,opt,name=scenario,proto3" json:"scenario,omitempty"`
	Unit     string         `protobuf:"bytes,5,opt,name=unit,proto3" json:"unit,omitempty"`
	Lang     string         `protobuf:"bytes,6,opt,name=lang,proto3" json:"lang,omitempty"`
	Concept  Concept        `protobuf:"varint,7,opt,name=concept,proto3,enum=asdf.xbrl.v2.Concept" json:"concept,omitempty"`
	// Types that are assignable to Value:
	//	*Fact_String_
	//	*Fact_Float64
	//	*Fact_Date
	//	*Fact_Enum
	Value isFact_Value `protobuf_oneof:"value"`
}

func (x *Fact) Reset() {
	*x = Fact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xbrl_v2_fact_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fact) ProtoMessage() {}

func (x *Fact) ProtoReflect() protoreflect.Message {
	mi := &file_xbrl_v2_fact_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fact.ProtoReflect.Descriptor instead.
func (*Fact) Descriptor() ([]byte, []int) {
	return file_xbrl_v2_fact_proto_rawDescGZIP(), []int{1}
}

func (x *Fact) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (m *Fact) GetPeriod_() isFact_Period_ {
	if m != nil {
		return m.Period_
	}
	return nil
}

func (x *Fact) GetPeriod() *Duration {
	if x, ok := x.GetPeriod_().(*Fact_Period); ok {
		return x.Period
	}
	return nil
}

func (x *Fact) GetInstant() *Date {
	if x, ok := x.GetPeriod_().(*Fact_Instant); ok {
		return x.Instant
	}
	return nil
}

func (x *Fact) GetScenario() *Scenario {
	if x != nil {
		return x.Scenario
	}
	return nil
}

func (x *Fact) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Fact) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *Fact) GetConcept() Concept {
	if x != nil {
		return x.Concept
	}
	return Concept_UNKNOWN
}

func (m *Fact) GetValue() isFact_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Fact) GetString_() string {
	if x, ok := x.GetValue().(*Fact_String_); ok {
		return x.String_
	}
	return ""
}

func (x *Fact) GetFloat64() float64 {
	if x, ok := x.GetValue().(*Fact_Float64); ok {
		return x.Float64
	}
	return 0
}

func (x *Fact) GetDate() *Date {
	if x, ok := x.GetValue().(*Fact_Date); ok {
		return x.Date
	}
	return nil
}

func (x *Fact) GetEnum() string {
	if x, ok := x.GetValue().(*Fact_Enum); ok {
		return x.Enum
	}
	return ""
}

type isFact_Period_ interface {
	isFact_Period_()
}

type Fact_Period struct {
	Period *Duration `protobuf:"bytes,2,opt,name=period,proto3,oneof"`
}

type Fact_Instant struct {
	Instant *Date `protobuf:"bytes,3,opt,name=instant,proto3,oneof"`
}

func (*Fact_Period) isFact_Period_() {}

func (*Fact_Instant) isFact_Period_() {}

type isFact_Value interface {
	isFact_Value()
}

type Fact_String_ struct {
	String_ string `protobuf:"bytes,8,opt,name=string,proto3,oneof"`
}

type Fact_Float64 struct {
	Float64 float64 `protobuf:"fixed64,9,opt,name=float64,proto3,oneof"`
}

type Fact_Date struct {
	Date *Date `protobuf:"bytes,10,opt,name=date,proto3,oneof"`
}

type Fact_Enum struct {
	Enum string `protobuf:"bytes,11,opt,name=enum,proto3,oneof"`
}

func (*Fact_String_) isFact_Value() {}

func (*Fact_Float64) isFact_Value() {}

func (*Fact_Date) isFact_Value() {}

func (*Fact_Enum) isFact_Value() {}

type Scenario_TypedMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dimension Concept `protobuf:"varint,1,opt,name=dimension,proto3,enum=asdf.xbrl.v2.Concept" json:"dimension,omitempty"` // IdentificationOfAuditorDimension
	Type      Concept `protobuf:"varint,2,opt,name=type,proto3,enum=asdf.xbrl.v2.Concept" json:"type,omitempty"`           // auditorIdentifier
	Member    string  `protobuf:"bytes,3,opt,name=member,proto3" json:"member,omitempty"`                                  // Revisor2
}

func (x *Scenario_TypedMember) Reset() {
	*x = Scenario_TypedMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xbrl_v2_fact_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Scenario_TypedMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scenario_TypedMember) ProtoMessage() {}

func (x *Scenario_TypedMember) ProtoReflect() protoreflect.Message {
	mi := &file_xbrl_v2_fact_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scenario_TypedMember.ProtoReflect.Descriptor instead.
func (*Scenario_TypedMember) Descriptor() ([]byte, []int) {
	return file_xbrl_v2_fact_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Scenario_TypedMember) GetDimension() Concept {
	if x != nil {
		return x.Dimension
	}
	return Concept_UNKNOWN
}

func (x *Scenario_TypedMember) GetType() Concept {
	if x != nil {
		return x.Type
	}
	return Concept_UNKNOWN
}

func (x *Scenario_TypedMember) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

type Scenario_ExplicitMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dimension Concept `protobuf:"varint,1,opt,name=dimension,proto3,enum=asdf.xbrl.v2.Concept" json:"dimension,omitempty"` // ClassesOfEquityDimension
	Type      Concept `protobuf:"varint,2,opt,name=type,proto3,enum=asdf.xbrl.v2.Concept" json:"type,omitempty"`           // RetainedEarningsMember
}

func (x *Scenario_ExplicitMember) Reset() {
	*x = Scenario_ExplicitMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xbrl_v2_fact_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Scenario_ExplicitMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scenario_ExplicitMember) ProtoMessage() {}

func (x *Scenario_ExplicitMember) ProtoReflect() protoreflect.Message {
	mi := &file_xbrl_v2_fact_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scenario_ExplicitMember.ProtoReflect.Descriptor instead.
func (*Scenario_ExplicitMember) Descriptor() ([]byte, []int) {
	return file_xbrl_v2_fact_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Scenario_ExplicitMember) GetDimension() Concept {
	if x != nil {
		return x.Dimension
	}
	return Concept_UNKNOWN
}

func (x *Scenario_ExplicitMember) GetType() Concept {
	if x != nil {
		return x.Type
	}
	return Concept_UNKNOWN
}

type Scenario_Member struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Member:
	//	*Scenario_Member_Typed
	//	*Scenario_Member_Explicit
	Member isScenario_Member_Member `protobuf_oneof:"member"`
}

func (x *Scenario_Member) Reset() {
	*x = Scenario_Member{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xbrl_v2_fact_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Scenario_Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scenario_Member) ProtoMessage() {}

func (x *Scenario_Member) ProtoReflect() protoreflect.Message {
	mi := &file_xbrl_v2_fact_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scenario_Member.ProtoReflect.Descriptor instead.
func (*Scenario_Member) Descriptor() ([]byte, []int) {
	return file_xbrl_v2_fact_proto_rawDescGZIP(), []int{0, 2}
}

func (m *Scenario_Member) GetMember() isScenario_Member_Member {
	if m != nil {
		return m.Member
	}
	return nil
}

func (x *Scenario_Member) GetTyped() *Scenario_TypedMember {
	if x, ok := x.GetMember().(*Scenario_Member_Typed); ok {
		return x.Typed
	}
	return nil
}

func (x *Scenario_Member) GetExplicit() *Scenario_ExplicitMember {
	if x, ok := x.GetMember().(*Scenario_Member_Explicit); ok {
		return x.Explicit
	}
	return nil
}

type isScenario_Member_Member interface {
	isScenario_Member_Member()
}

type Scenario_Member_Typed struct {
	Typed *Scenario_TypedMember `protobuf:"bytes,1,opt,name=typed,proto3,oneof"`
}

type Scenario_Member_Explicit struct {
	Explicit *Scenario_ExplicitMember `protobuf:"bytes,2,opt,name=explicit,proto3,oneof"`
}

func (*Scenario_Member_Typed) isScenario_Member_Member() {}

func (*Scenario_Member_Explicit) isScenario_Member_Member() {}

var File_xbrl_v2_fact_proto protoreflect.FileDescriptor

var file_xbrl_v2_fact_proto_rawDesc = []byte{
	0x0a, 0x12, 0x78, 0x62, 0x72, 0x6c, 0x2f, 0x76, 0x32, 0x2f, 0x66, 0x61, 0x63, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x73, 0x64, 0x66, 0x2e, 0x78, 0x62, 0x72, 0x6c, 0x2e,
	0x76, 0x32, 0x1a, 0x12, 0x78, 0x62, 0x72, 0x6c, 0x2f, 0x76, 0x32, 0x2f, 0x64, 0x61, 0x74, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x78, 0x62, 0x72, 0x6c, 0x2f, 0x76, 0x32, 0x2f,
	0x63, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd3, 0x03,
	0x0a, 0x08, 0x53, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x12, 0x37, 0x0a, 0x07, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x73,
	0x64, 0x66, 0x2e, 0x78, 0x62, 0x72, 0x6c, 0x2e, 0x76, 0x32, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x61,
	0x72, 0x69, 0x6f, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x1a, 0x85, 0x01, 0x0a, 0x0b, 0x54, 0x79, 0x70, 0x65, 0x64, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x33, 0x0a, 0x09, 0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x61, 0x73, 0x64, 0x66, 0x2e, 0x78, 0x62,
	0x72, 0x6c, 0x2e, 0x76, 0x32, 0x2e, 0x43, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74, 0x52, 0x09, 0x64,
	0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x61, 0x73, 0x64, 0x66, 0x2e, 0x78, 0x62,
	0x72, 0x6c, 0x2e, 0x76, 0x32, 0x2e, 0x43, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x1a, 0x70, 0x0a, 0x0e, 0x45,
	0x78, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x33, 0x0a,
	0x09, 0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x15, 0x2e, 0x61, 0x73, 0x64, 0x66, 0x2e, 0x78, 0x62, 0x72, 0x6c, 0x2e, 0x76, 0x32, 0x2e,
	0x43, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74, 0x52, 0x09, 0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x15, 0x2e, 0x61, 0x73, 0x64, 0x66, 0x2e, 0x78, 0x62, 0x72, 0x6c, 0x2e, 0x76, 0x32, 0x2e,
	0x43, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x1a, 0x93, 0x01,
	0x0a, 0x06, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x3a, 0x0a, 0x05, 0x74, 0x79, 0x70, 0x65,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x61, 0x73, 0x64, 0x66, 0x2e, 0x78,
	0x62, 0x72, 0x6c, 0x2e, 0x76, 0x32, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x2e,
	0x54, 0x79, 0x70, 0x65, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x48, 0x00, 0x52, 0x05, 0x74,
	0x79, 0x70, 0x65, 0x64, 0x12, 0x43, 0x0a, 0x08, 0x65, 0x78, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x61, 0x73, 0x64, 0x66, 0x2e, 0x78, 0x62,
	0x72, 0x6c, 0x2e, 0x76, 0x32, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x2e, 0x45,
	0x78, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x48, 0x00, 0x52,
	0x08, 0x65, 0x78, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x22, 0x9f, 0x03, 0x0a, 0x04, 0x46, 0x61, 0x63, 0x74, 0x12, 0x1f, 0x0a, 0x0b,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x30, 0x0a,
	0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x61, 0x73, 0x64, 0x66, 0x2e, 0x78, 0x62, 0x72, 0x6c, 0x2e, 0x76, 0x32, 0x2e, 0x44, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12,
	0x2e, 0x0a, 0x07, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x61, 0x73, 0x64, 0x66, 0x2e, 0x78, 0x62, 0x72, 0x6c, 0x2e, 0x76, 0x32, 0x2e,
	0x44, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x07, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x12,
	0x32, 0x0a, 0x08, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x61, 0x73, 0x64, 0x66, 0x2e, 0x78, 0x62, 0x72, 0x6c, 0x2e, 0x76, 0x32,
	0x2e, 0x53, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x52, 0x08, 0x73, 0x63, 0x65, 0x6e, 0x61,
	0x72, 0x69, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x12, 0x2f, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x61,
	0x73, 0x64, 0x66, 0x2e, 0x78, 0x62, 0x72, 0x6c, 0x2e, 0x76, 0x32, 0x2e, 0x43, 0x6f, 0x6e, 0x63,
	0x65, 0x70, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74, 0x12, 0x18, 0x0a, 0x06,
	0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x06,
	0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x07, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x36,
	0x34, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x48, 0x01, 0x52, 0x07, 0x66, 0x6c, 0x6f, 0x61, 0x74,
	0x36, 0x34, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x61, 0x73, 0x64, 0x66, 0x2e, 0x78, 0x62, 0x72, 0x6c, 0x2e, 0x76, 0x32, 0x2e,
	0x44, 0x61, 0x74, 0x65, 0x48, 0x01, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x04,
	0x65, 0x6e, 0x75, 0x6d, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x04, 0x65, 0x6e,
	0x75, 0x6d, 0x42, 0x08, 0x0a, 0x06, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x42, 0x07, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x72, 0x6f, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x78,
	0x62, 0x72, 0x6c, 0x2f, 0x76, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_xbrl_v2_fact_proto_rawDescOnce sync.Once
	file_xbrl_v2_fact_proto_rawDescData = file_xbrl_v2_fact_proto_rawDesc
)

func file_xbrl_v2_fact_proto_rawDescGZIP() []byte {
	file_xbrl_v2_fact_proto_rawDescOnce.Do(func() {
		file_xbrl_v2_fact_proto_rawDescData = protoimpl.X.CompressGZIP(file_xbrl_v2_fact_proto_rawDescData)
	})
	return file_xbrl_v2_fact_proto_rawDescData
}

var file_xbrl_v2_fact_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_xbrl_v2_fact_proto_goTypes = []interface{}{
	(*Scenario)(nil),                // 0: asdf.xbrl.v2.Scenario
	(*Fact)(nil),                    // 1: asdf.xbrl.v2.Fact
	(*Scenario_TypedMember)(nil),    // 2: asdf.xbrl.v2.Scenario.TypedMember
	(*Scenario_ExplicitMember)(nil), // 3: asdf.xbrl.v2.Scenario.ExplicitMember
	(*Scenario_Member)(nil),         // 4: asdf.xbrl.v2.Scenario.Member
	(*Duration)(nil),                // 5: asdf.xbrl.v2.Duration
	(*Date)(nil),                    // 6: asdf.xbrl.v2.Date
	(Concept)(0),                    // 7: asdf.xbrl.v2.Concept
}
var file_xbrl_v2_fact_proto_depIdxs = []int32{
	4,  // 0: asdf.xbrl.v2.Scenario.members:type_name -> asdf.xbrl.v2.Scenario.Member
	5,  // 1: asdf.xbrl.v2.Fact.period:type_name -> asdf.xbrl.v2.Duration
	6,  // 2: asdf.xbrl.v2.Fact.instant:type_name -> asdf.xbrl.v2.Date
	0,  // 3: asdf.xbrl.v2.Fact.scenario:type_name -> asdf.xbrl.v2.Scenario
	7,  // 4: asdf.xbrl.v2.Fact.concept:type_name -> asdf.xbrl.v2.Concept
	6,  // 5: asdf.xbrl.v2.Fact.date:type_name -> asdf.xbrl.v2.Date
	7,  // 6: asdf.xbrl.v2.Scenario.TypedMember.dimension:type_name -> asdf.xbrl.v2.Concept
	7,  // 7: asdf.xbrl.v2.Scenario.TypedMember.type:type_name -> asdf.xbrl.v2.Concept
	7,  // 8: asdf.xbrl.v2.Scenario.ExplicitMember.dimension:type_name -> asdf.xbrl.v2.Concept
	7,  // 9: asdf.xbrl.v2.Scenario.ExplicitMember.type:type_name -> asdf.xbrl.v2.Concept
	2,  // 10: asdf.xbrl.v2.Scenario.Member.typed:type_name -> asdf.xbrl.v2.Scenario.TypedMember
	3,  // 11: asdf.xbrl.v2.Scenario.Member.explicit:type_name -> asdf.xbrl.v2.Scenario.ExplicitMember
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_xbrl_v2_fact_proto_init() }
func file_xbrl_v2_fact_proto_init() {
	if File_xbrl_v2_fact_proto != nil {
		return
	}
	file_xbrl_v2_date_proto_init()
	file_xbrl_v2_concept_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_xbrl_v2_fact_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Scenario); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xbrl_v2_fact_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xbrl_v2_fact_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Scenario_TypedMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xbrl_v2_fact_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Scenario_ExplicitMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xbrl_v2_fact_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Scenario_Member); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_xbrl_v2_fact_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Fact_Period)(nil),
		(*Fact_Instant)(nil),
		(*Fact_String_)(nil),
		(*Fact_Float64)(nil),
		(*Fact_Date)(nil),
		(*Fact_Enum)(nil),
	}
	file_xbrl_v2_fact_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*Scenario_Member_Typed)(nil),
		(*Scenario_Member_Explicit)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xbrl_v2_fact_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xbrl_v2_fact_proto_goTypes,
		DependencyIndexes: file_xbrl_v2_fact_proto_depIdxs,
		MessageInfos:      file_xbrl_v2_fact_proto_msgTypes,
	}.Build()
	File_xbrl_v2_fact_proto = out.File
	file_xbrl_v2_fact_proto_rawDesc = nil
	file_xbrl_v2_fact_proto_goTypes = nil
	file_xbrl_v2_fact_proto_depIdxs = nil
}
