# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xbrl/v2/fact.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from xbrl.v2 import date_pb2 as xbrl_dot_v2_dot_date__pb2
from xbrl.v2 import concept_pb2 as xbrl_dot_v2_dot_concept__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='xbrl/v2/fact.proto',
  package='asdf.xbrl.v2',
  syntax='proto3',
  serialized_options=b'Z\035github.com/hroi/proto/xbrl/v2',
  serialized_pb=b'\n\x12xbrl/v2/fact.proto\x12\x0c\x61sdf.xbrl.v2\x1a\x12xbrl/v2/date.proto\x1a\x15xbrl/v2/concept.proto\"\x8e\x03\n\x08Scenario\x12.\n\x07members\x18\x01 \x03(\x0b\x32\x1d.asdf.xbrl.v2.Scenario.Member\x1al\n\x0bTypedMember\x12(\n\tdimension\x18\x01 \x01(\x0e\x32\x15.asdf.xbrl.v2.Concept\x12#\n\x04type\x18\x02 \x01(\x0e\x32\x15.asdf.xbrl.v2.Concept\x12\x0e\n\x06member\x18\x03 \x01(\t\x1a_\n\x0e\x45xplicitMember\x12(\n\tdimension\x18\x01 \x01(\x0e\x32\x15.asdf.xbrl.v2.Concept\x12#\n\x04type\x18\x02 \x01(\x0e\x32\x15.asdf.xbrl.v2.Concept\x1a\x82\x01\n\x06Member\x12\x33\n\x05typed\x18\x01 \x01(\x0b\x32\".asdf.xbrl.v2.Scenario.TypedMemberH\x00\x12\x39\n\x08\x65xplicit\x18\x02 \x01(\x0b\x32%.asdf.xbrl.v2.Scenario.ExplicitMemberH\x00\x42\x08\n\x06member\"\xc6\x02\n\x04\x46\x61\x63t\x12\x13\n\x0binstance_id\x18\x01 \x01(\x03\x12(\n\x06period\x18\x02 \x01(\x0b\x32\x16.asdf.xbrl.v2.DurationH\x00\x12%\n\x07instant\x18\x03 \x01(\x0b\x32\x12.asdf.xbrl.v2.DateH\x00\x12(\n\x08scenario\x18\x04 \x01(\x0b\x32\x16.asdf.xbrl.v2.Scenario\x12\x0c\n\x04unit\x18\x05 \x01(\t\x12\x0c\n\x04lang\x18\x06 \x01(\t\x12&\n\x07\x63oncept\x18\x07 \x01(\x0e\x32\x15.asdf.xbrl.v2.Concept\x12\x10\n\x06string\x18\x08 \x01(\tH\x01\x12\x11\n\x07\x66loat64\x18\t \x01(\x01H\x01\x12\"\n\x04\x64\x61te\x18\n \x01(\x0b\x32\x12.asdf.xbrl.v2.DateH\x01\x12\x0e\n\x04\x65num\x18\x0b \x01(\tH\x01\x42\x08\n\x06PeriodB\x07\n\x05valueB\x1fZ\x1dgithub.com/hroi/proto/xbrl/v2b\x06proto3'
  ,
  dependencies=[xbrl_dot_v2_dot_date__pb2.DESCRIPTOR,xbrl_dot_v2_dot_concept__pb2.DESCRIPTOR,])




_SCENARIO_TYPEDMEMBER = _descriptor.Descriptor(
  name='TypedMember',
  full_name='asdf.xbrl.v2.Scenario.TypedMember',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dimension', full_name='asdf.xbrl.v2.Scenario.TypedMember.dimension', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='asdf.xbrl.v2.Scenario.TypedMember.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='member', full_name='asdf.xbrl.v2.Scenario.TypedMember.member', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=248,
)

_SCENARIO_EXPLICITMEMBER = _descriptor.Descriptor(
  name='ExplicitMember',
  full_name='asdf.xbrl.v2.Scenario.ExplicitMember',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dimension', full_name='asdf.xbrl.v2.Scenario.ExplicitMember.dimension', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='asdf.xbrl.v2.Scenario.ExplicitMember.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=345,
)

_SCENARIO_MEMBER = _descriptor.Descriptor(
  name='Member',
  full_name='asdf.xbrl.v2.Scenario.Member',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='typed', full_name='asdf.xbrl.v2.Scenario.Member.typed', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='explicit', full_name='asdf.xbrl.v2.Scenario.Member.explicit', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='member', full_name='asdf.xbrl.v2.Scenario.Member.member',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=348,
  serialized_end=478,
)

_SCENARIO = _descriptor.Descriptor(
  name='Scenario',
  full_name='asdf.xbrl.v2.Scenario',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='members', full_name='asdf.xbrl.v2.Scenario.members', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SCENARIO_TYPEDMEMBER, _SCENARIO_EXPLICITMEMBER, _SCENARIO_MEMBER, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=478,
)


_FACT = _descriptor.Descriptor(
  name='Fact',
  full_name='asdf.xbrl.v2.Fact',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='asdf.xbrl.v2.Fact.instance_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='period', full_name='asdf.xbrl.v2.Fact.period', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instant', full_name='asdf.xbrl.v2.Fact.instant', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scenario', full_name='asdf.xbrl.v2.Fact.scenario', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unit', full_name='asdf.xbrl.v2.Fact.unit', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lang', full_name='asdf.xbrl.v2.Fact.lang', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='concept', full_name='asdf.xbrl.v2.Fact.concept', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='string', full_name='asdf.xbrl.v2.Fact.string', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='float64', full_name='asdf.xbrl.v2.Fact.float64', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date', full_name='asdf.xbrl.v2.Fact.date', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enum', full_name='asdf.xbrl.v2.Fact.enum', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Period', full_name='asdf.xbrl.v2.Fact.Period',
      index=0, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='value', full_name='asdf.xbrl.v2.Fact.value',
      index=1, containing_type=None, fields=[]),
  ],
  serialized_start=481,
  serialized_end=807,
)

_SCENARIO_TYPEDMEMBER.fields_by_name['dimension'].enum_type = xbrl_dot_v2_dot_concept__pb2._CONCEPT
_SCENARIO_TYPEDMEMBER.fields_by_name['type'].enum_type = xbrl_dot_v2_dot_concept__pb2._CONCEPT
_SCENARIO_TYPEDMEMBER.containing_type = _SCENARIO
_SCENARIO_EXPLICITMEMBER.fields_by_name['dimension'].enum_type = xbrl_dot_v2_dot_concept__pb2._CONCEPT
_SCENARIO_EXPLICITMEMBER.fields_by_name['type'].enum_type = xbrl_dot_v2_dot_concept__pb2._CONCEPT
_SCENARIO_EXPLICITMEMBER.containing_type = _SCENARIO
_SCENARIO_MEMBER.fields_by_name['typed'].message_type = _SCENARIO_TYPEDMEMBER
_SCENARIO_MEMBER.fields_by_name['explicit'].message_type = _SCENARIO_EXPLICITMEMBER
_SCENARIO_MEMBER.containing_type = _SCENARIO
_SCENARIO_MEMBER.oneofs_by_name['member'].fields.append(
  _SCENARIO_MEMBER.fields_by_name['typed'])
_SCENARIO_MEMBER.fields_by_name['typed'].containing_oneof = _SCENARIO_MEMBER.oneofs_by_name['member']
_SCENARIO_MEMBER.oneofs_by_name['member'].fields.append(
  _SCENARIO_MEMBER.fields_by_name['explicit'])
_SCENARIO_MEMBER.fields_by_name['explicit'].containing_oneof = _SCENARIO_MEMBER.oneofs_by_name['member']
_SCENARIO.fields_by_name['members'].message_type = _SCENARIO_MEMBER
_FACT.fields_by_name['period'].message_type = xbrl_dot_v2_dot_date__pb2._DURATION
_FACT.fields_by_name['instant'].message_type = xbrl_dot_v2_dot_date__pb2._DATE
_FACT.fields_by_name['scenario'].message_type = _SCENARIO
_FACT.fields_by_name['concept'].enum_type = xbrl_dot_v2_dot_concept__pb2._CONCEPT
_FACT.fields_by_name['date'].message_type = xbrl_dot_v2_dot_date__pb2._DATE
_FACT.oneofs_by_name['Period'].fields.append(
  _FACT.fields_by_name['period'])
_FACT.fields_by_name['period'].containing_oneof = _FACT.oneofs_by_name['Period']
_FACT.oneofs_by_name['Period'].fields.append(
  _FACT.fields_by_name['instant'])
_FACT.fields_by_name['instant'].containing_oneof = _FACT.oneofs_by_name['Period']
_FACT.oneofs_by_name['value'].fields.append(
  _FACT.fields_by_name['string'])
_FACT.fields_by_name['string'].containing_oneof = _FACT.oneofs_by_name['value']
_FACT.oneofs_by_name['value'].fields.append(
  _FACT.fields_by_name['float64'])
_FACT.fields_by_name['float64'].containing_oneof = _FACT.oneofs_by_name['value']
_FACT.oneofs_by_name['value'].fields.append(
  _FACT.fields_by_name['date'])
_FACT.fields_by_name['date'].containing_oneof = _FACT.oneofs_by_name['value']
_FACT.oneofs_by_name['value'].fields.append(
  _FACT.fields_by_name['enum'])
_FACT.fields_by_name['enum'].containing_oneof = _FACT.oneofs_by_name['value']
DESCRIPTOR.message_types_by_name['Scenario'] = _SCENARIO
DESCRIPTOR.message_types_by_name['Fact'] = _FACT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Scenario = _reflection.GeneratedProtocolMessageType('Scenario', (_message.Message,), {

  'TypedMember' : _reflection.GeneratedProtocolMessageType('TypedMember', (_message.Message,), {
    'DESCRIPTOR' : _SCENARIO_TYPEDMEMBER,
    '__module__' : 'xbrl.v2.fact_pb2'
    # @@protoc_insertion_point(class_scope:asdf.xbrl.v2.Scenario.TypedMember)
    })
  ,

  'ExplicitMember' : _reflection.GeneratedProtocolMessageType('ExplicitMember', (_message.Message,), {
    'DESCRIPTOR' : _SCENARIO_EXPLICITMEMBER,
    '__module__' : 'xbrl.v2.fact_pb2'
    # @@protoc_insertion_point(class_scope:asdf.xbrl.v2.Scenario.ExplicitMember)
    })
  ,

  'Member' : _reflection.GeneratedProtocolMessageType('Member', (_message.Message,), {
    'DESCRIPTOR' : _SCENARIO_MEMBER,
    '__module__' : 'xbrl.v2.fact_pb2'
    # @@protoc_insertion_point(class_scope:asdf.xbrl.v2.Scenario.Member)
    })
  ,
  'DESCRIPTOR' : _SCENARIO,
  '__module__' : 'xbrl.v2.fact_pb2'
  # @@protoc_insertion_point(class_scope:asdf.xbrl.v2.Scenario)
  })
_sym_db.RegisterMessage(Scenario)
_sym_db.RegisterMessage(Scenario.TypedMember)
_sym_db.RegisterMessage(Scenario.ExplicitMember)
_sym_db.RegisterMessage(Scenario.Member)

Fact = _reflection.GeneratedProtocolMessageType('Fact', (_message.Message,), {
  'DESCRIPTOR' : _FACT,
  '__module__' : 'xbrl.v2.fact_pb2'
  # @@protoc_insertion_point(class_scope:asdf.xbrl.v2.Fact)
  })
_sym_db.RegisterMessage(Fact)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
