# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xbrl/v2/instance.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from xbrl.v2 import entity_pb2 as xbrl_dot_v2_dot_entity__pb2
from xbrl.v2 import date_pb2 as xbrl_dot_v2_dot_date__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='xbrl/v2/instance.proto',
  package='asdf.xbrl.v2',
  syntax='proto3',
  serialized_options=b'Z\035github.com/hroi/proto/xbrl/v2',
  serialized_pb=b'\n\x16xbrl/v2/instance.proto\x12\x0c\x61sdf.xbrl.v2\x1a\x14xbrl/v2/entity.proto\x1a\x12xbrl/v2/date.proto\"m\n\x08Instance\x12\x13\n\x0binstance_id\x18\x01 \x01(\x03\x12$\n\x06\x65ntity\x18\x02 \x01(\x0b\x32\x14.asdf.xbrl.v2.Entity\x12&\n\x06period\x18\x03 \x01(\x0b\x32\x16.asdf.xbrl.v2.DurationB\x1fZ\x1dgithub.com/hroi/proto/xbrl/v2b\x06proto3'
  ,
  dependencies=[xbrl_dot_v2_dot_entity__pb2.DESCRIPTOR,xbrl_dot_v2_dot_date__pb2.DESCRIPTOR,])




_INSTANCE = _descriptor.Descriptor(
  name='Instance',
  full_name='asdf.xbrl.v2.Instance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='asdf.xbrl.v2.Instance.instance_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entity', full_name='asdf.xbrl.v2.Instance.entity', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='period', full_name='asdf.xbrl.v2.Instance.period', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=191,
)

_INSTANCE.fields_by_name['entity'].message_type = xbrl_dot_v2_dot_entity__pb2._ENTITY
_INSTANCE.fields_by_name['period'].message_type = xbrl_dot_v2_dot_date__pb2._DURATION
DESCRIPTOR.message_types_by_name['Instance'] = _INSTANCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Instance = _reflection.GeneratedProtocolMessageType('Instance', (_message.Message,), {
  'DESCRIPTOR' : _INSTANCE,
  '__module__' : 'xbrl.v2.instance_pb2'
  # @@protoc_insertion_point(class_scope:asdf.xbrl.v2.Instance)
  })
_sym_db.RegisterMessage(Instance)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
