# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xbrl/v2/instance.proto

require 'google/protobuf'

require 'xbrl/v2/entity_pb'
require 'xbrl/v2/date_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("xbrl/v2/instance.proto", :syntax => :proto3) do
    add_message "asdf.xbrl.v2.Instance" do
      optional :instance_id, :int64, 1
      optional :entity, :message, 2, "asdf.xbrl.v2.Entity"
      optional :period, :message, 3, "asdf.xbrl.v2.Duration"
    end
  end
end

module Asdf
  module Xbrl
    module V2
      Instance = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asdf.xbrl.v2.Instance").msgclass
    end
  end
end
