// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.0
// 	protoc        v3.11.4
// source: xbrl/v2/instance.proto

package v2

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Instance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstanceId int64     `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Entity     *Entity   `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	Period     *Duration `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"`
}

func (x *Instance) Reset() {
	*x = Instance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xbrl_v2_instance_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_xbrl_v2_instance_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_xbrl_v2_instance_proto_rawDescGZIP(), []int{0}
}

func (x *Instance) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *Instance) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *Instance) GetPeriod() *Duration {
	if x != nil {
		return x.Period
	}
	return nil
}

var File_xbrl_v2_instance_proto protoreflect.FileDescriptor

var file_xbrl_v2_instance_proto_rawDesc = []byte{
	0x0a, 0x16, 0x78, 0x62, 0x72, 0x6c, 0x2f, 0x76, 0x32, 0x2f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x73, 0x64, 0x66, 0x2e, 0x78,
	0x62, 0x72, 0x6c, 0x2e, 0x76, 0x32, 0x1a, 0x14, 0x78, 0x62, 0x72, 0x6c, 0x2f, 0x76, 0x32, 0x2f,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x78, 0x62,
	0x72, 0x6c, 0x2f, 0x76, 0x32, 0x2f, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x89, 0x01, 0x0a, 0x08, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x2c,
	0x0a, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x61, 0x73, 0x64, 0x66, 0x2e, 0x78, 0x62, 0x72, 0x6c, 0x2e, 0x76, 0x32, 0x2e, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x52, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x2e, 0x0a, 0x06,
	0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61,
	0x73, 0x64, 0x66, 0x2e, 0x78, 0x62, 0x72, 0x6c, 0x2e, 0x76, 0x32, 0x2e, 0x44, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x42, 0x1f, 0x5a, 0x1d,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x72, 0x6f, 0x69, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x78, 0x62, 0x72, 0x6c, 0x2f, 0x76, 0x32, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_xbrl_v2_instance_proto_rawDescOnce sync.Once
	file_xbrl_v2_instance_proto_rawDescData = file_xbrl_v2_instance_proto_rawDesc
)

func file_xbrl_v2_instance_proto_rawDescGZIP() []byte {
	file_xbrl_v2_instance_proto_rawDescOnce.Do(func() {
		file_xbrl_v2_instance_proto_rawDescData = protoimpl.X.CompressGZIP(file_xbrl_v2_instance_proto_rawDescData)
	})
	return file_xbrl_v2_instance_proto_rawDescData
}

var file_xbrl_v2_instance_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_xbrl_v2_instance_proto_goTypes = []interface{}{
	(*Instance)(nil), // 0: asdf.xbrl.v2.Instance
	(*Entity)(nil),   // 1: asdf.xbrl.v2.Entity
	(*Duration)(nil), // 2: asdf.xbrl.v2.Duration
}
var file_xbrl_v2_instance_proto_depIdxs = []int32{
	1, // 0: asdf.xbrl.v2.Instance.entity:type_name -> asdf.xbrl.v2.Entity
	2, // 1: asdf.xbrl.v2.Instance.period:type_name -> asdf.xbrl.v2.Duration
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_xbrl_v2_instance_proto_init() }
func file_xbrl_v2_instance_proto_init() {
	if File_xbrl_v2_instance_proto != nil {
		return
	}
	file_xbrl_v2_entity_proto_init()
	file_xbrl_v2_date_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_xbrl_v2_instance_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Instance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xbrl_v2_instance_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xbrl_v2_instance_proto_goTypes,
		DependencyIndexes: file_xbrl_v2_instance_proto_depIdxs,
		MessageInfos:      file_xbrl_v2_instance_proto_msgTypes,
	}.Build()
	File_xbrl_v2_instance_proto = out.File
	file_xbrl_v2_instance_proto_rawDesc = nil
	file_xbrl_v2_instance_proto_goTypes = nil
	file_xbrl_v2_instance_proto_depIdxs = nil
}
