# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xbrl/v2/type.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='xbrl/v2/type.proto',
  package='asdf.xbrl.v2',
  syntax='proto3',
  serialized_options=b'Z\035github.com/hroi/proto/xbrl/v2',
  serialized_pb=b'\n\x12xbrl/v2/type.proto\x12\x0c\x61sdf.xbrl.v2\"\x06\n\x04TypeB\x1fZ\x1dgithub.com/hroi/proto/xbrl/v2b\x06proto3'
)




_TYPE = _descriptor.Descriptor(
  name='Type',
  full_name='asdf.xbrl.v2.Type',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=42,
)

DESCRIPTOR.message_types_by_name['Type'] = _TYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Type = _reflection.GeneratedProtocolMessageType('Type', (_message.Message,), {
  'DESCRIPTOR' : _TYPE,
  '__module__' : 'xbrl.v2.type_pb2'
  # @@protoc_insertion_point(class_scope:asdf.xbrl.v2.Type)
  })
_sym_db.RegisterMessage(Type)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
