# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xbrl/v2/type.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("xbrl/v2/type.proto", :syntax => :proto3) do
    add_message "asdf.xbrl.v2.Type" do
    end
  end
end

module Asdf
  module Xbrl
    module V2
      Type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asdf.xbrl.v2.Type").msgclass
    end
  end
end
