# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xbrl/v1/instance.proto

require 'google/protobuf'

require 'types/date_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("xbrl/v1/instance.proto", :syntax => :proto3) do
    add_message "asdf.xbrl.v1.Entity" do
      optional :scheme, :string, 1
      optional :identifier, :string, 2
    end
    add_message "asdf.xbrl.v1.Instance" do
      optional :instance_id, :int64, 1
    end
    add_message "asdf.xbrl.v1.Context" do
      optional :context_id, :int64, 1
      optional :instance_id, :int64, 2
      optional :entity, :message, 3, "asdf.xbrl.v1.Entity"
      optional :period, :message, 4, "asdf.types.Daterange"
      optional :name, :string, 5
    end
    add_message "asdf.xbrl.v1.Unit" do
      optional :unit_id, :int64, 1
      optional :instance_id, :int64, 2
      optional :name, :string, 3
      optional :measure, :string, 4
    end
    add_message "asdf.xbrl.v1.Fact" do
      optional :fact_id, :int64, 1
      optional :context_id, :int64, 2
      optional :unit_id, :int64, 3
      optional :concept_id, :int64, 4
      optional :lang, :string, 10
      optional :decimals, :int32, 11
      optional :precision, :int32, 12
      oneof :value do
        optional :numeric, :float, 5
        optional :text, :string, 6
        optional :date, :string, 7
        optional :bool, :bool, 8
        optional :enum_id, :int32, 9
      end
    end
  end
end

module Asdf
  module Xbrl
    module V1
      Entity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asdf.xbrl.v1.Entity").msgclass
      Instance = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asdf.xbrl.v1.Instance").msgclass
      Context = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asdf.xbrl.v1.Context").msgclass
      Unit = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asdf.xbrl.v1.Unit").msgclass
      Fact = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asdf.xbrl.v1.Fact").msgclass
    end
  end
end
