# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xbrl/v1/rpc.proto

require 'google/protobuf'

require 'xbrl/v1/taxonomy_pb'
require 'xbrl/v1/instance_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("xbrl/v1/rpc.proto", :syntax => :proto3) do
    add_message "asdf.xbrl.v1.GetTaxonomyRequest" do
      oneof :get_by do
        optional :taxonomy_id, :int32, 1
        optional :taxonomy_prefix, :string, 2
        optional :taxonomy_namespace, :string, 3
      end
    end
    add_message "asdf.xbrl.v1.GetTaxonomyReply" do
      optional :taxonomy, :message, 1, "asdf.xbrl.v1.Taxonomy"
      map :taxonomies, :int32, :message, 2, "asdf.xbrl.v1.Taxonomy"
      map :types, :int32, :message, 3, "asdf.xbrl.v1.Type"
      map :enums, :int32, :message, 4, "asdf.xbrl.v1.Enum"
      map :concepts, :int32, :message, 5, "asdf.xbrl.v1.Concept"
    end
    add_message "asdf.xbrl.v1.GetInstanceRequest" do
      oneof :get_by do
        optional :instance_id, :int64, 1
      end
    end
    add_message "asdf.xbrl.v1.GetInstanceReply" do
      optional :instance, :message, 1, "asdf.xbrl.v1.Instance"
      map :contexts, :int64, :message, 2, "asdf.xbrl.v1.Context"
      map :units, :int64, :message, 3, "asdf.xbrl.v1.Unit"
      map :facts, :int64, :message, 4, "asdf.xbrl.v1.Fact"
      map :taxonomies, :int32, :message, 5, "asdf.xbrl.v1.Taxonomy"
      map :concepts, :int32, :message, 6, "asdf.xbrl.v1.Concept"
      map :types, :int32, :message, 7, "asdf.xbrl.v1.Type"
      map :enums, :int32, :message, 8, "asdf.xbrl.v1.Enum"
    end
  end
end

module Asdf
  module Xbrl
    module V1
      GetTaxonomyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asdf.xbrl.v1.GetTaxonomyRequest").msgclass
      GetTaxonomyReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asdf.xbrl.v1.GetTaxonomyReply").msgclass
      GetInstanceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asdf.xbrl.v1.GetInstanceRequest").msgclass
      GetInstanceReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asdf.xbrl.v1.GetInstanceReply").msgclass
    end
  end
end
