# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xbrl/v1/taxonomy.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='xbrl/v1/taxonomy.proto',
  package='asdf.xbrl.v1',
  syntax='proto3',
  serialized_options=b'Z\035github.com/hroi/proto/xbrl/v1',
  serialized_pb=b'\n\x16xbrl/v1/taxonomy.proto\x12\x0c\x61sdf.xbrl.v1\"B\n\x08Taxonomy\x12\x13\n\x0btaxonomy_id\x18\x01 \x01(\x05\x12\x11\n\tnamespace\x18\x02 \x01(\t\x12\x0e\n\x06prefix\x18\x03 \x01(\t\"R\n\x04Type\x12\x0f\n\x07type_id\x18\x01 \x01(\x05\x12\x16\n\x0eparent_type_id\x18\x02 \x01(\x05\x12\x13\n\x0btaxonomy_id\x18\x03 \x01(\x05\x12\x0c\n\x04name\x18\x04 \x01(\t\"7\n\x04\x45num\x12\x0f\n\x07\x65num_id\x18\x01 \x01(\x05\x12\x0f\n\x07type_id\x18\x02 \x01(\x05\x12\r\n\x05value\x18\x03 \x01(\t\"\xbd\x01\n\x07\x43oncept\x12\x12\n\nconcept_id\x18\x01 \x01(\x05\x12\x13\n\x0btaxonomy_id\x18\x02 \x01(\x05\x12\x0f\n\x07type_id\x18\x03 \x01(\x05\x12\x0c\n\x04name\x18\x04 \x01(\t\x12-\n\x0bperiod_type\x18\x05 \x01(\x0e\x32\x18.asdf.xbrl.v1.PeriodType\x12&\n\x07\x62\x61lance\x18\x06 \x01(\x0e\x32\x15.asdf.xbrl.v1.Balance\x12\x13\n\x0bis_abstract\x18\x07 \x01(\x08\"^\n\x0c\x43onceptLabel\x12\x10\n\x08label_id\x18\x01 \x01(\x05\x12\x12\n\nconcept_id\x18\x02 \x01(\x05\x12\x0c\n\x04lang\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\x12\x0c\n\x04text\x18\x05 \x01(\t*B\n\x0bTypeStorage\x12\x0b\n\x07NUMERIC\x10\x00\x12\x08\n\x04TEXT\x10\x01\x12\x08\n\x04\x44\x41TE\x10\x02\x12\x08\n\x04\x42OOL\x10\x04\x12\x08\n\x04\x45NUM\x10\x05*\'\n\nPeriodType\x12\x0c\n\x08\x44URATION\x10\x00\x12\x0b\n\x07INSTANT\x10\x01* \n\x07\x42\x61lance\x12\t\n\x05\x44\x45\x42IT\x10\x00\x12\n\n\x06\x43REDIT\x10\x01\x42\x1fZ\x1dgithub.com/hroi/proto/xbrl/v1b\x06proto3'
)

_TYPESTORAGE = _descriptor.EnumDescriptor(
  name='TypeStorage',
  full_name='asdf.xbrl.v1.TypeStorage',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NUMERIC', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEXT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DATE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BOOL', index=3, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENUM', index=4, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=537,
  serialized_end=603,
)
_sym_db.RegisterEnumDescriptor(_TYPESTORAGE)

TypeStorage = enum_type_wrapper.EnumTypeWrapper(_TYPESTORAGE)
_PERIODTYPE = _descriptor.EnumDescriptor(
  name='PeriodType',
  full_name='asdf.xbrl.v1.PeriodType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DURATION', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INSTANT', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=605,
  serialized_end=644,
)
_sym_db.RegisterEnumDescriptor(_PERIODTYPE)

PeriodType = enum_type_wrapper.EnumTypeWrapper(_PERIODTYPE)
_BALANCE = _descriptor.EnumDescriptor(
  name='Balance',
  full_name='asdf.xbrl.v1.Balance',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEBIT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CREDIT', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=646,
  serialized_end=678,
)
_sym_db.RegisterEnumDescriptor(_BALANCE)

Balance = enum_type_wrapper.EnumTypeWrapper(_BALANCE)
NUMERIC = 0
TEXT = 1
DATE = 2
BOOL = 4
ENUM = 5
DURATION = 0
INSTANT = 1
DEBIT = 0
CREDIT = 1



_TAXONOMY = _descriptor.Descriptor(
  name='Taxonomy',
  full_name='asdf.xbrl.v1.Taxonomy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='taxonomy_id', full_name='asdf.xbrl.v1.Taxonomy.taxonomy_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='namespace', full_name='asdf.xbrl.v1.Taxonomy.namespace', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prefix', full_name='asdf.xbrl.v1.Taxonomy.prefix', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=106,
)


_TYPE = _descriptor.Descriptor(
  name='Type',
  full_name='asdf.xbrl.v1.Type',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type_id', full_name='asdf.xbrl.v1.Type.type_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parent_type_id', full_name='asdf.xbrl.v1.Type.parent_type_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='taxonomy_id', full_name='asdf.xbrl.v1.Type.taxonomy_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='asdf.xbrl.v1.Type.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=190,
)


_ENUM = _descriptor.Descriptor(
  name='Enum',
  full_name='asdf.xbrl.v1.Enum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='enum_id', full_name='asdf.xbrl.v1.Enum.enum_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type_id', full_name='asdf.xbrl.v1.Enum.type_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='asdf.xbrl.v1.Enum.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=247,
)


_CONCEPT = _descriptor.Descriptor(
  name='Concept',
  full_name='asdf.xbrl.v1.Concept',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='concept_id', full_name='asdf.xbrl.v1.Concept.concept_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='taxonomy_id', full_name='asdf.xbrl.v1.Concept.taxonomy_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type_id', full_name='asdf.xbrl.v1.Concept.type_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='asdf.xbrl.v1.Concept.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='period_type', full_name='asdf.xbrl.v1.Concept.period_type', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='balance', full_name='asdf.xbrl.v1.Concept.balance', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_abstract', full_name='asdf.xbrl.v1.Concept.is_abstract', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=439,
)


_CONCEPTLABEL = _descriptor.Descriptor(
  name='ConceptLabel',
  full_name='asdf.xbrl.v1.ConceptLabel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label_id', full_name='asdf.xbrl.v1.ConceptLabel.label_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='concept_id', full_name='asdf.xbrl.v1.ConceptLabel.concept_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lang', full_name='asdf.xbrl.v1.ConceptLabel.lang', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='role', full_name='asdf.xbrl.v1.ConceptLabel.role', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='asdf.xbrl.v1.ConceptLabel.text', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=441,
  serialized_end=535,
)

_CONCEPT.fields_by_name['period_type'].enum_type = _PERIODTYPE
_CONCEPT.fields_by_name['balance'].enum_type = _BALANCE
DESCRIPTOR.message_types_by_name['Taxonomy'] = _TAXONOMY
DESCRIPTOR.message_types_by_name['Type'] = _TYPE
DESCRIPTOR.message_types_by_name['Enum'] = _ENUM
DESCRIPTOR.message_types_by_name['Concept'] = _CONCEPT
DESCRIPTOR.message_types_by_name['ConceptLabel'] = _CONCEPTLABEL
DESCRIPTOR.enum_types_by_name['TypeStorage'] = _TYPESTORAGE
DESCRIPTOR.enum_types_by_name['PeriodType'] = _PERIODTYPE
DESCRIPTOR.enum_types_by_name['Balance'] = _BALANCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Taxonomy = _reflection.GeneratedProtocolMessageType('Taxonomy', (_message.Message,), {
  'DESCRIPTOR' : _TAXONOMY,
  '__module__' : 'xbrl.v1.taxonomy_pb2'
  # @@protoc_insertion_point(class_scope:asdf.xbrl.v1.Taxonomy)
  })
_sym_db.RegisterMessage(Taxonomy)

Type = _reflection.GeneratedProtocolMessageType('Type', (_message.Message,), {
  'DESCRIPTOR' : _TYPE,
  '__module__' : 'xbrl.v1.taxonomy_pb2'
  # @@protoc_insertion_point(class_scope:asdf.xbrl.v1.Type)
  })
_sym_db.RegisterMessage(Type)

Enum = _reflection.GeneratedProtocolMessageType('Enum', (_message.Message,), {
  'DESCRIPTOR' : _ENUM,
  '__module__' : 'xbrl.v1.taxonomy_pb2'
  # @@protoc_insertion_point(class_scope:asdf.xbrl.v1.Enum)
  })
_sym_db.RegisterMessage(Enum)

Concept = _reflection.GeneratedProtocolMessageType('Concept', (_message.Message,), {
  'DESCRIPTOR' : _CONCEPT,
  '__module__' : 'xbrl.v1.taxonomy_pb2'
  # @@protoc_insertion_point(class_scope:asdf.xbrl.v1.Concept)
  })
_sym_db.RegisterMessage(Concept)

ConceptLabel = _reflection.GeneratedProtocolMessageType('ConceptLabel', (_message.Message,), {
  'DESCRIPTOR' : _CONCEPTLABEL,
  '__module__' : 'xbrl.v1.taxonomy_pb2'
  # @@protoc_insertion_point(class_scope:asdf.xbrl.v1.ConceptLabel)
  })
_sym_db.RegisterMessage(ConceptLabel)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
