# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xbrl/v1/taxonomy.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("xbrl/v1/taxonomy.proto", :syntax => :proto3) do
    add_message "asdf.xbrl.v1.Taxonomy" do
      optional :taxonomy_id, :int32, 1
      optional :namespace, :string, 2
      optional :prefix, :string, 3
    end
    add_message "asdf.xbrl.v1.Type" do
      optional :type_id, :int32, 1
      optional :parent_type_id, :int32, 2
      optional :taxonomy_id, :int32, 3
      optional :name, :string, 4
    end
    add_message "asdf.xbrl.v1.Enum" do
      optional :enum_id, :int32, 1
      optional :type_id, :int32, 2
      optional :value, :string, 3
    end
    add_message "asdf.xbrl.v1.Concept" do
      optional :concept_id, :int32, 1
      optional :taxonomy_id, :int32, 2
      optional :type_id, :int32, 3
      optional :name, :string, 4
      optional :period_type, :enum, 5, "asdf.xbrl.v1.PeriodType"
      optional :balance, :enum, 6, "asdf.xbrl.v1.Balance"
      optional :is_abstract, :bool, 7
    end
    add_message "asdf.xbrl.v1.ConceptLabel" do
      optional :label_id, :int32, 1
      optional :concept_id, :int32, 2
      optional :lang, :string, 3
      optional :role, :string, 4
      optional :text, :string, 5
    end
    add_enum "asdf.xbrl.v1.TypeStorage" do
      value :NUMERIC, 0
      value :TEXT, 1
      value :DATE, 2
      value :BOOL, 4
      value :ENUM, 5
    end
    add_enum "asdf.xbrl.v1.PeriodType" do
      value :DURATION, 0
      value :INSTANT, 1
    end
    add_enum "asdf.xbrl.v1.Balance" do
      value :DEBIT, 0
      value :CREDIT, 1
    end
  end
end

module Asdf
  module Xbrl
    module V1
      Taxonomy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asdf.xbrl.v1.Taxonomy").msgclass
      Type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asdf.xbrl.v1.Type").msgclass
      Enum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asdf.xbrl.v1.Enum").msgclass
      Concept = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asdf.xbrl.v1.Concept").msgclass
      ConceptLabel = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asdf.xbrl.v1.ConceptLabel").msgclass
      TypeStorage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asdf.xbrl.v1.TypeStorage").enummodule
      PeriodType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asdf.xbrl.v1.PeriodType").enummodule
      Balance = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asdf.xbrl.v1.Balance").enummodule
    end
  end
end
